version: "2"

services:
  app:
    image: golang:1.13.7-alpine
    volumes:
      - .:/go/go-worker-pool-poc
    working_dir: /go/go-worker-pool-poc
    command: go run main.go
    ports:
      - "8000:8000"
    links:
      - redis
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"